In [1]:
import pandas as pd

In [6]:
zone_vs_setor_df = pd.read_excel("Bases_setores_cd.xlsx", sheet_name = "Setor vs Zoneamento")

In [7]:
zone_vs_setor_df

       CD_RE  CD_GV  CD_SETOR  CD_GRUPO CD_ZONEAMENTO
0          7    255      3648     25988     PE0135005
1          2    240      3267     20352     SP0635002
2          2    241      3831     20435     SP0066005
3          3    237      3410     21813     RJ0041105
4          6    230      3604     23846     TO0075505
...      ...    ...       ...       ...           ...
53892      7    257      3575     23553     RN0121005
53893      4    233      3296     20630     BA0046005
53894      6    230      3603     23835     DF0001005
53895      8    246      3437     22092     MA2111301
53896      1    268      3463     22377     RS0216005

[53897 rows x 5 columns]

In [41]:
re_por_zoneamento_df = (
    zone_vs_setor_df
    .groupby("CD_ZONEAMENTO", as_index=False)
    .agg(
        QTD_RE=("CD_RE", "nunique")
    )
    .sort_values("QTD_RE", ascending=False)
)

re_por_zoneamento_df

     CD_ZONEAMENTO  QTD_RE
2647     MG0702005       7
5941     SP0100402       7
5969     SP0100431       7
1291     GO0014005       6
4018     PR0083005       6
...            ...     ...
6820     TO1713809       1
618      BA0304005       1
6822     TO1845105       1
6823     TO1850105       1
5        AC0002005       1

[6825 rows x 2 columns]

In [9]:
zoneamentos_por_setor_df = (
    zone_vs_setor_df
    .groupby("CD_SETOR", as_index=False)
    .agg(
        QTD_ZONEAMENTOS=("CD_ZONEAMENTO", "nunique")
    )
    .sort_values("QTD_ZONEAMENTOS", ascending=False)
)

zoneamentos_por_setor_df

     CD_SETOR  QTD_ZONEAMENTOS
258      3459              118
495      3722               84
523      3752               78
607      3856               77
315      3518               72
..        ...              ...
15       3202                6
342      3549                6
288      3491                6
235      3435                6
310      3513                4

[620 rows x 2 columns]

In [26]:
setor_por_zoneamentos_df = (
    zone_vs_setor_df
    .groupby("CD_ZONEAMENTO", as_index=False)
    .agg(
        QTD_SETORES=("CD_SETOR", "nunique")
    )
    .sort_values("QTD_SETORES", ascending=False)
)

setor_por_zoneamentos_df

     CD_ZONEAMENTO  QTD_SETORES
5969     SP0100431           40
5941     SP0100402           38
5980     SP0100451           32
5945     SP0100407           30
5940     SP0100401           30
...            ...          ...
6814     TO0212505            1
6813     TO0212005            1
6812     TO0211005            1
6809     TO0209705            1
6808     TO0209305            1

[6825 rows x 2 columns]

In [ ]:
zone_vs_setor_df[zone_vs_setor_df["CD_SETOR"]==3459]

       CD_RE  CD_GV  CD_SETOR  CD_GRUPO CD_ZONEAMENTO
259        5    263      3459     22972     SP0256200
605        5    263      3459     22967     SP0304900
621        5    263      3459     22972     SP0369005
724        5    263      3459     22967     SP0359010
1129       5    263      3459     22972     SP0138505
...      ...    ...       ...       ...           ...
51431      5    263      3459     22972     SP0300005
51548      5    263      3459     22972     SP0549005
51741      5    263      3459     22972     SP0445005
53117      5    263      3459     22331     SP0405400
53241      5    263      3459     22332     SP0198005

[128 rows x 5 columns]

In [47]:
len(set(zone_vs_setor_df["CD_GRUPO"]))

5456

In [11]:
gvs_por_setor_df = (
    zone_vs_setor_df
    .groupby("CD_SETOR", as_index=False)
    .agg(
        QTD_GVS=("CD_GV", "nunique")
    )
    .sort_values("QTD_GVS", ascending=False)
)

gvs_por_setor_df

     CD_SETOR  QTD_GVS
0        3184        1
1        3185        1
2        3186        1
3        3187        1
4        3188        1
..        ...      ...
615      3865        1
616      3866        1
617      3867        1
618      4012        1
619      4074        1

[620 rows x 2 columns]

In [13]:
gerencias_por_setor_df = (
    zone_vs_setor_df
    .groupby("CD_SETOR", as_index=False)
    .agg(
        QTD_GERENCIAS_VENDAS=("CD_GV", "nunique")
    )
    .sort_values("QTD_GERENCIAS_VENDAS", ascending=False)
)

gerencias_por_setor_df

     CD_SETOR  QTD_GERENCIAS_VENDAS
0        3184                     1
1        3185                     1
2        3186                     1
3        3187                     1
4        3188                     1
..        ...                   ...
615      3865                     1
616      3866                     1
617      3867                     1
618      4012                     1
619      4074                     1

[620 rows x 2 columns]

In [16]:
# Quantidade de GRUPOS distintos por GV
grupos_por_gv_df = (
    zone_vs_setor_df
    .groupby("CD_GV", as_index=False)
    .agg(
        QTD_GRUPOS=("CD_GRUPO", "nunique")
    )
    .sort_values("QTD_GRUPOS", ascending=False)
)

grupos_por_gv_df

    CD_GV  QTD_GRUPOS
13    244         212
17    249         205
14    246         197
24    256         191
19    251         186
2     232         185
18    250         184
7     237         169
6     236         166
16    248         162
32    264         159
22    254         158
11    242         157
23    255         155
26    258         155
9     240         152
21    253         149
3     233         148
1     230         142
12    243         138
5     235         138
31    263         138
30    262         136
27    259         135
28    260         135
36    268         133
0     229         133
34    266         132
25    257         128
20    252         125
8     239         124
35    267         122
29    261         120
4     234         119
33    265         117
15    247          93
10    241          87

In [17]:
# Quantidade de GVs distintos por GRUPO
gvs_por_grupo_df = (
    zone_vs_setor_df
    .groupby("CD_GRUPO", as_index=False)
    .agg(
        QTD_GVS=("CD_GV", "nunique")
    )
    .sort_values("QTD_GVS", ascending=False)
)

gvs_por_grupo_df

      CD_GRUPO  QTD_GVS
0            0       30
1        19518        1
2        19519        1
3        19521        1
4        19522        1
...        ...      ...
5451     26520        1
5452     26521        1
5453     26522        1
5454     26523        1
5455     26524        1

[5456 rows x 2 columns]

In [20]:
zone_vs_setor_df[zone_vs_setor_df["CD_GRUPO"]==0]

       CD_RE  CD_GV  CD_SETOR  CD_GRUPO CD_ZONEAMENTO
1009       4    235      3408         0     MG0493005
2601       1    267      3428         0     PR0108005
2971       7    255      3486         0     PE0141005
2986       3    237      3708         0     RJ0017005
3730       7    252      3391         0     PE0011005
...      ...    ...       ...       ...           ...
52036      3    236      3777         0     RJ0045504
52464      6    230      3288         0     SE0003005
53021      1    264      3546         0     SC0050005
53368      4    235      3408         0     MG0376005
53651      2    240      3231         0     SP0100451

[80 rows x 5 columns]

In [21]:
setores_por_grupo_df = (
    zone_vs_setor_df
    .groupby("CD_GRUPO", as_index=False)
    .agg(
        QTD_SETORES=("CD_SETOR", "nunique")
    )
    .sort_values("QTD_SETORES", ascending=False)
)

setores_por_grupo_df

      CD_GRUPO  QTD_SETORES
0            0           70
1        19518            1
2        19519            1
3        19521            1
4        19522            1
...        ...          ...
5451     26520            1
5452     26521            1
5453     26522            1
5454     26523            1
5455     26524            1

[5456 rows x 2 columns]

In [22]:
grupos_por_setor_df = (
    zone_vs_setor_df
    .groupby("CD_SETOR", as_index=False)
    .agg(
        QTD_GRUPOS=("CD_GRUPO", "nunique")
    )
    .sort_values("QTD_GRUPOS", ascending=False)
)

grupos_por_setor_df

     CD_SETOR  QTD_GRUPOS
380      3591          14
39       3228          14
405      3618          14
184      3381          14
283      3486          13
..        ...         ...
333      3540           6
44       3233           6
314      3517           6
27       3215           6
359      3567           5

[620 rows x 2 columns]

In [23]:
# Quantidade de zoneamentos distintos por grupo
zoneamentos_por_grupo_df = (
    zone_vs_setor_df
    .groupby("CD_GRUPO", as_index=False)
    .agg(
        QTD_ZONEAMENTOS=("CD_ZONEAMENTO", "nunique")
    )
    .sort_values("QTD_ZONEAMENTOS", ascending=False)
)

zoneamentos_por_grupo_df

      CD_GRUPO  QTD_ZONEAMENTOS
0            0               76
702      20416               47
698      20410               46
703      20417               43
2613     22861               41
...        ...              ...
3686     24168                1
2663     22924                1
2662     22923                1
966      20739                1
963      20735                1

[5456 rows x 2 columns]

In [24]:
# Quantidade de grupos distintos por zoneamento
grupos_por_zoneamento_df = (
    zone_vs_setor_df
    .groupby("CD_ZONEAMENTO", as_index=False)
    .agg(
        QTD_GRUPOS=("CD_GRUPO", "nunique")
    )
    .sort_values("QTD_GRUPOS", ascending=False)
)

grupos_por_zoneamento_df

     CD_ZONEAMENTO  QTD_GRUPOS
5941     SP0100402         135
5945     SP0100407         119
5980     SP0100451         117
5940     SP0100401         116
5978     SP0100449         116
...            ...         ...
397      BA0136035           1
3609     PE0410610           1
6806     TO0208505           1
6788     TO0186505           1
6787     TO0185505           1

[6825 rows x 2 columns]

In [27]:
# Quantidade de REs distintos por GV
res_por_gv_df = (
    zone_vs_setor_df
    .groupby("CD_GV", as_index=False)
    .agg(
        QTD_RES=("CD_RE", "nunique")
    )
    .sort_values("QTD_RES", ascending=False)
)

res_por_gv_df

    CD_GV  QTD_RES
0     229        1
1     230        1
2     232        1
3     233        1
4     234        1
5     235        1
6     236        1
7     237        1
8     239        1
9     240        1
10    241        1
11    242        1
12    243        1
13    244        1
14    246        1
15    247        1
16    248        1
17    249        1
18    250        1
19    251        1
20    252        1
21    253        1
22    254        1
23    255        1
24    256        1
25    257        1
26    258        1
27    259        1
28    260        1
29    261        1
30    262        1
31    263        1
32    264        1
33    265        1
34    266        1
35    267        1
36    268        1

In [28]:
gvs_por_re_df = (
    zone_vs_setor_df
    .groupby("CD_RE", as_index=False)
    .agg(
        QTD_GVS=("CD_GV", "nunique")
    )
    .sort_values("QTD_GVS", ascending=False)
)

gvs_por_re_df

   CD_RE  QTD_GVS
6      7       10
7      8        6
0      1        5
1      2        4
3      4        3
2      3        3
5      6        3
4      5        3

In [33]:
gl_df = pd.read_excel("Bases_setores_cd.xlsx", sheet_name = "GI")

In [34]:
gl_df

,MARCA,CENTRO,UF,ZONEAMENTO PARTIDA,NOME CIDADE,ROTA,PRAZO DE TRP,PRAZO TOTAL
0,NATURA / AVON VD,5700,AM,SP0084005,EIRUNEPE,104493,19,20
1,NATURA / AVON VD,5700,AM,SP0084005,IPIXUNA,104493,19,20
2,NATURA / AVON VD,5700,AM,SP0084005,ENVIRA,104493,18,19
3,NATURA / AVON VD,5700,AM,SP0084005,CANUTAMA,104494,18,19
4,NATURA / AVON VD,5300,AM,AM1302606,ITAMARATI,6522,18,19
...,...,...,...,...,...,...,...,...
8904,NATURA / AVON VD,5100,CE,AL0055005,CAUCAIA,5621,2,2
8905,NATURA / AVON VD,5100,RN,AL0055005,CEARA MIRIM,5302,2,2
8906,NATURA / AVON VD,5700,SP,SP0084005,PEDREIRA,101007,1,2
8907,NATURA / AVON VD,5600,MG,MG0702005,UBERLANDIA,703030,1,2
8908,NATURA / AVON VD,5400,RS,RS0031005,CANOAS,205110,2,2

In [35]:
zoneamentos_por_centro_df = (
    gl_df
    .groupby("CENTRO", as_index=False)
    .agg(
        QTD_ZONEAMENTOS=("ZONEAMENTO PARTIDA", "nunique")
    )
    .sort_values("QTD_ZONEAMENTOS", ascending=False)
)

zoneamentos_por_centro_df

   CENTRO  QTD_ZONEAMENTOS
0    2700                1
1    2800                1
2    5100                1
3    5300                1
4    5400                1
5    5500                1
6    5600                1
7    5700                1
8    5800                1

In [36]:
centros_por_zoneamento_df = (
    gl_df
    .groupby("ZONEAMENTO PARTIDA", as_index=False)
    .agg(
        QTD_CENTROS=("CENTRO", "nunique")
    )
    .sort_values("QTD_CENTROS", ascending=False)
)

centros_por_zoneamento_df

  ZONEAMENTO PARTIDA  QTD_CENTROS
0          AL0055005            1
1          AM1302606            1
2          BA0307005            1
3          MG0408005            1
4          MG0702005            1
5          PA0024005            1
6          RS0031005            1
7          SP0084005            1
8          SP0100421            1

In [40]:
zoneamentos_mg = sorted(
    zone_vs_setor_df.loc[
        zone_vs_setor_df["CD_ZONEAMENTO"].str.startswith("MG", na=False),
        "CD_ZONEAMENTO"
    ].unique()
)

zoneamentos_mg

['MG0001005',
 'MG0002005',
 'MG0003005',
 'MG0004005',
 'MG0005005',
 'MG0005025',
 'MG0005035',
 'MG0006005',
 'MG0006805',
 'MG0007005',
 'MG0008005',
 'MG0009005',
 'MG0010005',
 'MG0010010',
 'MG0011005',
 'MG0012005',
 'MG0013005',
 'MG0014005',
 'MG0015005',
 'MG0016005',
 'MG0017005',
 'MG0017015',
 'MG0018005',
 'MG0019005',
 'MG0019010',
 'MG0020005',
 'MG0021005',
 'MG0021010',
 'MG0021020',
 'MG0022005',
 'MG0023005',
 'MG0024005',
 'MG0025005',
 'MG0026005',
 'MG0027005',
 'MG0027073',
 'MG0028005',
 'MG0028505',
 'MG0029005',
 'MG0030005',
 'MG0031005',
 'MG0032005',
 'MG0033005',
 'MG0034005',
 'MG0035005',
 'MG0036005',
 'MG0037005',
 'MG0038005',
 'MG0039005',
 'MG0039410',
 'MG0040005',
 'MG0041005',
 'MG0042005',
 'MG0043005',
 'MG0043920',
 'MG0044005',
 'MG0045005',
 'MG0046005',
 'MG0047005',
 'MG0047010',
 'MG0047956',
 'MG0048005',
 'MG0049005',
 'MG0050005',
 'MG0050028',
 'MG0051005',
 'MG0052005',
 'MG0052402',
 'MG0053005',
 'MG0054005',
 'MG0055005',
 'MG0056005',
 'MG0057005',
 'MG0057377',
 'MG0059005',
 'MG0059100',
 'MG0060005',
 'MG0061005',
 'MG0062005',
 'MG0062006',
 'MG0062010',
 'MG0062011',
 'MG0062012',
 'MG0062022',
 'MG0063005',
 'MG0063010',
 'MG0064005',
 'MG0065005',
 'MG0066005',
 'MG0066505',
 'MG0067005',
 'MG0067010',
 'MG0068051',
 'MG0069005',
 'MG0070005',
 'MG0071071',
 'MG0072005',
 'MG0073005',
 'MG0074005',
 'MG0075005',
 'MG0076005',
 'MG0077005',
 'MG0078005',
 'MG0079005',
 'MG0080005',
 'MG0081005',
 'MG0082005',
 'MG0083005',
 'MG0084005',
 'MG0085005',
 'MG0086005',
 'MG0086015',
 'MG0086022',
 'MG0086025',
 'MG0087005',
 'MG0088005',
 'MG0089005',
 'MG0090005',
 'MG0091005',
 'MG0092005',
 'MG0092505',
 'MG0093005',
 'MG0094005',
 'MG0094010',
 'MG0094505',
 'MG0095005',
 'MG0096005',
 'MG0097005',
 'MG0098005',
 'MG0099005',
 'MG0100005',
 'MG0101005',
 'MG0102005',
 'MG0103005',
 'MG0104005',
 'MG0105005',
 'MG0105010',
 'MG0106005',
 'MG0106015',
 'MG0107005',
 'MG0108005',
 'MG0108010',
 'MG0109005',
 'MG0110005',
 'MG0111005',
 'MG0111010',
 'MG0112005',
 'MG0113005',
 'MG0114005',
 'MG0115005',
 'MG0116005',
 'MG0116010',
 'MG0117005',
 'MG0118005',
 'MG0119005',
 'MG0120005',
 'MG0120505',
 'MG0121005',
 'MG0121010',
 'MG0122005',
 'MG0123005',
 'MG0124005',
 'MG0125005',
 'MG0126005',
 'MG0127005',
 'MG0128005',
 'MG0129005',
 'MG0130005',
 'MG0131005',
 'MG0132005',
 'MG0133005',
 'MG0133015',
 'MG0134005',
 'MG0134060',
 'MG0135005',
 'MG0136005',
 'MG0137005',
 'MG0138005',
 'MG0139005',
 'MG0140005',
 'MG0141005',
 'MG0142005',
 'MG0143005',
 'MG0144005',
 'MG0145005',
 'MG0146005',
 'MG0147005',
 'MG0148005',
 'MG0149005',
 'MG0150005',
 'MG0151005',
 'MG0152005',
 'MG0153005',
 'MG0154005',
 'MG0154505',
 'MG0154705',
 'MG0155005',
 'MG0156005',
 'MG0157005',
 'MG0157010',
 'MG0158005',
 'MG0159005',
 'MG0160005',
 'MG0161005',
 'MG0161505',
 'MG0162005',
 'MG0164005',
 'MG0165005',
 'MG0166005',
 'MG0167005',
 'MG0168005',
 'MG0169005',
 'MG0170005',
 'MG0171005',
 'MG0172005',
 'MG0173005',
 'MG0174005',
 'MG0175005',
 'MG0176005',
 'MG0177005',
 'MG0178005',
 'MG0178305',
 'MG0179005',
 'MG0180005',
 'MG0181005',
 'MG0182005',
 'MG0183005',
 'MG0184005',
 'MG0184015',
 'MG0184030',
 'MG0184040',
 'MG0185005',
 'MG0186005',
 'MG0187005',
 'MG0188005',
 'MG0188030',
 'MG0188035',
 'MG0189005',
 'MG0190005',
 'MG0191005',
 'MG0192005',
 'MG0193005',
 'MG0194005',
 'MG0195005',
 'MG0196005',
 'MG0197005',
 'MG0198005',
 'MG0199005',
 'MG0199505',
 'MG0200000',
 'MG0201005',
 'MG0201505',
 'MG0202005',
 'MG0203005',
 'MG0204005',
 'MG0205005',
 'MG0206005',
 'MG0207005',
 'MG0207010',
 'MG0208005',
 'MG0209005',
 'MG0210005',
 'MG0211005',
 'MG0212005',
 'MG0212505',
 'MG0213005',
 'MG0214005',
 'MG0215005',
 'MG0216005',
 'MG0216015',
 'MG0216045',
 'MG0216050',
 'MG0217005',
 'MG0218005',
 'MG0219005',
 'MG0220005',
 'MG0221005',
 'MG0222005',
 'MG0223005',
 'MG0223505',
 'MG0224005',
 'MG0224505',
 'MG0224705',
 'MG0225005',
 'MG0226005',
 'MG0227005',
 'MG0228005',
 'MG0229005',
 'MG0230005',
 'MG0231005',
 'MG0232005',
 'MG0233005',
 'MG0234005',
 'MG0235005',
 'MG0236005',
 'MG0237005',
 'MG0238005',
 'MG0238505',
 'MG0239005',
 'MG0240005',
 'MG0241005',
 'MG0242005',
 'MG0243005',
 'MG0244005',
 'MG0245005',
 'MG0246005',
 'MG0247005',
 'MG0248005',
 'MG0249005',
 'MG0250005',
 'MG0251005',
 'MG0252005',
 'MG0253005',
 'MG0254005',
 'MG0255005',
 'MG0256005',
 'MG0257005',
 'MG0258005',
 'MG0259005',
 'MG0260005',
 'MG0261005',
 'MG0262005',
 'MG0263005',
 'MG0264005',
 'MG0265010',
 'MG0266005',
 'MG0267005',
 'MG0267010',
 'MG0268005',
 'MG0269005',
 'MG0269505',
 'MG0270005',
 'MG0270505',
 'MG0271005',
 'MG0271010',
 'MG0272005',
 'MG0273005',
 'MG0274005',
 'MG0275005',
 'MG0276005',
 'MG0277005',
 'MG0277015',
 'MG0277025',
 'MG0278005',
 'MG0279005',
 'MG0280005',
 'MG0280010',
 'MG0281005',
 'MG0282005',
 'MG0283005',
 'MG0284005',
 'MG0285005',
 'MG0286005',
 'MG0287005',
 'MG0288005',
 'MG0289005',
 'MG0290005',
 'MG0291005',
 'MG0291010',
 'MG0292005',
 'MG0293005',
 'MG0294005',
 'MG0295005',
 'MG0296005',
 'MG0296505',
 'MG0297005',
 'MG0298005',
 'MG0298007',
 'MG0298015',
 'MG0299005',
 'MG0300005',
 'MG0300505',
 'MG0301005',
 'MG0301010',
 'MG0302005',
 'MG0303005',
 'MG0304005',
 'MG0305005',
 'MG0305505',
 'MG0306005',
 'MG0307005',
 'MG0308005',
 'MG0309005',
 'MG0309020',
 'MG0310005',
 'MG0311005',
 'MG0311505',
 'MG0312005',
 'MG0313005',
 'MG0314005',
 'MG0315005',
 'MG0316005',
 'MG0317005',
 'MG0318005',
 'MG0319005',
 'MG0320005',
 'MG0321005',
 'MG0321010',
 'MG0322005',
 'MG0323005',
 'MG0324005',
 'MG0325005',
 'MG0325010',
 'MG0326005',
 'MG0327005',
 'MG0328005',
 'MG0330005',
 'MG0331005',
 'MG0332005',
 'MG0332010',
 'MG0333005',
 'MG0334005',
 'MG0335005',
 'MG0335010',
 'MG0335015',
 'MG0336005',
 'MG0337005',
 'MG0338005',
 'MG0339005',
 'MG0340005',
 'MG0341005',
 'MG0342005',
 'MG0343005',
 'MG0343010',
 'MG0344005',
 'MG0344015',
 'MG0344025',
 'MG0344030',
 'MG0344035',
 'MG0345005',
 'MG0346005',
 'MG0347005',
 'MG0348005',
 'MG0349005',
 'MG0350005',
 'MG0350505',
 'MG0351005',
 'MG0352005',
 'MG0352010',
 'MG0353005',
 'MG0354015',
 'MG0354505',
 'MG0355005',
 'MG0356005',
 'MG0357005',
 'MG0358005',
 'MG0359005',
 'MG0360005',
 'MG0361005',
 'MG0362005',
 'MG0363005',
 'MG0363017',
 'MG0363030',
 'MG0364005',
 'MG0365005',
 'MG0365205',
 'MG0365505',
 'MG0365705',
 'MG0366005',
 'MG0367005',
 'MG0368005',
 'MG0368010',
 'MG0369005',
 'MG0370005',
 'MG0371005',
 'MG0372005',
 'MG0373005',
 'MG0374005',
 'MG0375005',
 'MG0376005',
 'MG0376010',
 'MG0377005',
 'MG0378005',
 'MG0379005',
 'MG0380005',
 'MG0381005',
 'MG0382005',
 'MG0383005',
 'MG0383505',
 'MG0384005',
 'MG0385005',
 'MG0386005',
 'MG0386705',
 'MG0387005',
 'MG0388005',
 'MG0389005',
 'MG0390005',
 'MG0391005',
 'MG0392005',
 'MG0392015',
 'MG0393005',
 'MG0393007',
 'MG0393030',
 'MG0394005',
 'MG0394020',
 'MG0395005',
 'MG0395010',
 'MG0395015',
 'MG0396005',
 'MG0396020',
 'MG0396025',
 'MG0397005',
 'MG0398005',
 'MG0399005',
 'MG0400005',
 'MG0400006',
 'MG0400050',
 'MG0401005',
 'MG0402005',
 'MG0403005',
 'MG0404005',
 'MG0405005',
 'MG0405015',
 'MG0405505',
 'MG0406005',
 'MG0407005',
 'MG0407015',
 'MG0408005',
 'MG0409005',
 'MG0411005',
 'MG0412005',
 'MG0413005',
 'MG0414005',
 'MG0415005',
 'MG0416005',
 'MG0417005',
 'MG0417010',
 'MG0418005',
 'MG0419005',
 'MG0420005',
 'MG0421005',
 'MG0422005',
 'MG0422505',
 'MG0423005',
 'MG0424005',
 'MG0425005',
 'MG0426005',
 'MG0427005',
 'MG0428005',
 'MG0429005',
 'MG0429010',
 'MG0430005',
 'MG0431005',
 'MG0432005',
 'MG0433005',
 'MG0434005',
 'MG0435005',
 'MG0436005',
 'MG0437005',
 'MG0438005',
 'MG0439005',
 'MG0439010',
 'MG0439040',
 'MG0440005',
 'MG0441005',
 'MG0442005',
 'MG0443005',
 'MG0443705',
 'MG0444005',
 'MG0445005',
 'MG0446005',
 'MG0446505',
 'MG0447005',
 'MG0448005',
 'MG0449005',
 'MG0450005',
 'MG0450505',
 'MG0451005',
 'MG0452005',
 'MG0453005',
 'MG0453505',
 'MG0453705',
 'MG0454005',
 'MG0454505',
 'MG0455005',
 'MG0456005',
 'MG0457005',
 'MG0458005',
 'MG0458505',
 'MG0458705',
 'MG0459005',
 'MG0460005',
 'MG0461005',
 'MG0461006',
 'MG0461010',
 'MG0461020',
 'MG0461025',
 'MG0461035',
 'MG0461040',
 'MG0461045',
 'MG0462005',
 'MG0462505',
 'MG0463005',
 'MG0463010',
 'MG0464005',
 'MG0465005',
 'MG0465505',
 'MG0466005',
 'MG0467005',
 'MG0469005',
 'MG0470005',
 'MG0471005',
 'MG0472005',
 'MG0473005',
 'MG0474005',
 'MG0475005',
 'MG0476005',
 'MG0477005',
 'MG0478005',
 'MG0479005',
 'MG0480005',
 'MG0480030',
 'MG0481005',
 'MG0482005',
 'MG0483005',
 'MG0484005',
 'MG0485005',
 'MG0486005',
 'MG0487005',
 'MG0487505',
 'MG0488005',
 'MG0489005',
 'MG0490005',
 'MG0491005',
 'MG0491505',
 'MG0492005',
 'MG0493005',
 'MG0495005',
 'MG0496005',
 'MG0497005',
 'MG0498005',
 'MG0499005',
 'MG0500005',
 'MG0500415',
 'MG0501005',
 'MG0501505',
 'MG0502005',
 'MG0503005',
 'MG0504005',
 'MG0505005',
 'MG0505305',
 'MG0505705',
 'MG0506005',
 'MG0506410',
 'MG0507005',
 'MG0508005',
 'MG0509005',
 'MG0510005',
 'MG0511005',
 'MG0512005',
 'MG0512305',
 'MG0513005',
 'MG0514005',
 'MG0515005',
 'MG0516005',
 'MG0517005',
 'MG0518005',
 'MG0519005',
 'MG0520005',
 'MG0521005',
 'MG0521705',
 'MG0522005',
 'MG0523005',
 'MG0524005',
 'MG0525005',
 'MG0526005',
 'MG0526010',
 'MG0527005',
 'MG0528005',
 'MG0529005',
 'MG0529010',
 'MG0530005',
 'MG0531005',
 'MG0532005',
 'MG0533005',
 'MG0534005',
 'MG0534015',
 'MG0535005',
 'MG0536005',
 'MG0537005',
 'MG0538005',
 'MG0539005',
 'MG0540005',
 'MG0540010',
 'MG0541005',
 'MG0542005',
 'MG0543005',
 'MG0544005',
 'MG0544010',
 'MG0545005',
 'MG0546005',
 'MG0547005',
 'MG0548005',
 'MG0549005',
 'MG0550005',
 'MG0551005',
 'MG0551015',
 'MG0552005',
 'MG0553005',
 'MG0554005',
 'MG0554010',
 'MG0555005',
 'MG0556005',
 'MG0556010',
 'MG0556015',
 'MG0556030',
 'MG0557005',
 'MG0558005',
 'MG0559005',
 'MG0560005',
 'MG0561005',
 'MG0562005',
 'MG0563005',
 'MG0564005',
 'MG0565005',
 'MG0566005',
 'MG0567005',
 'MG0568005',
 'MG0569005',
 'MG0570005',
 'MG0571005',
 'MG0572005',
 'MG0572020',
 'MG0572505',
 'MG0572705',
 'MG0573005',
 'MG0574005',
 'MG0575005',
 'MG0576005',
 'MG0576505',
 'MG0577005',
 'MG0578005',
 'MG0579005',
 'MG0580005',
 'MG0581005',
 'MG0582005',
 'MG0583005',
 'MG0584005',
 'MG0585005',
 'MG0586005',
 'MG0587005',
 'MG0588005',
 'MG0589005',
 'MG0590005',
 'MG0590010',
 'MG0592005',
 'MG0593005',
 'MG0593505',
 'MG0594005',
 'MG0595005',
 'MG0596005',
 'MG0597005',
 'MG0598005',
 'MG0598010',
 'MG0599005',
 'MG0600005',
 'MG0600010',
 'MG0601005',
 'MG0602005',
 'MG0603005',
 'MG0604005',
 'MG0604505',
 'MG0605005',
 'MG0606005',
 'MG0607005',
 'MG0608005',
 'MG0609005',
 'MG0609505',
 'MG0610005',
 'MG0610505',
 'MG0611005',
 'MG0611025',
 'MG0612005',
 'MG0613005',
 'MG0614005',
 'MG0615005',
 'MG0616005',
 'MG0616505',
 'MG0617005',
 'MG0617015',
 'MG0618005',
 'MG0619005',
 'MG0620005',
 'MG0621005',
 'MG0621015',
 'MG0622005',
 'MG0623005',
 'MG0624005',
 'MG0624015',
 'MG0625005',
 'MG0626005',
 'MG0627005',
 'MG0628005',
 'MG0629005',
 'MG0629505',
 'MG0630005',
 'MG0631005',
 'MG0632005',
 'MG0633005',
 'MG0634005',
 'MG0635005',
 'MG0636005',
 'MG0637005',
 'MG0638005',
 'MG0639005',
 'MG0640005',
 'MG0641005',
 'MG0642005',
 'MG0642010',
 'MG0643005',
 'MG0644005',
 'MG0644305',
 'MG0645005',
 'MG0646005',
 'MG0647005',
 'MG0648005',
 'MG0649005',
 'MG0650005',
 'MG0651005',
 'MG0652005',
 'MG0653005',
 'MG0654005',
 'MG0655005',
 'MG0655505',
 'MG0655605',
 'MG0656005',
 'MG0657005',
 'MG0658005',
 'MG0659005',
 'MG0660005',
 'MG0661005',
 'MG0662005',
 'MG0663005',
 'MG0664005',
 'MG0665005',
 'MG0666005',
 'MG0667005',
 'MG0668005',
 'MG0669005',
 'MG0669505',
 'MG0670005',
 'MG0671005',
 'MG0672005',
 'MG0673005',
 'MG0674005',
 'MG0675005',
 'MG0676005',
 'MG0677005',
 'MG0678005',
 'MG0679005',
 'MG0680005',
 'MG0681005',
 'MG0682005',
 'MG0683005',
 'MG0684005',
 'MG0685005',
 'MG0686005',
 'MG0687005',
 'MG0688005',
 'MG0688010',
 'MG0689005',
 'MG0690005',
 'MG0691005',
 'MG0692005',
 'MG0693005',
 'MG0693505',
 'MG0694005',
 'MG0695005',
 'MG0696005',
 'MG0696010',
 'MG0697005',
 'MG0698005',
 'MG0699005',
 'MG0700005',
 'MG0700505',
 'MG0701005',
 'MG0702005',
 'MG0703005',
 'MG0704005',
 'MG0704030',
 'MG0705005',
 'MG0706005',
 'MG0707005',
 'MG0708005',
 'MG0709005',
 'MG0709025',
 'MG0710005',
 'MG0710505',
 'MG0711005',
 'MG0712005',
 'MG0713005',
 'MG0714005',
 'MG0715005',
 'MG0716005',
 'MG0717005',
 'MG0718005',
 'MG0719005',
 'MG0721005',
 'MG0722005',
 'MG0945120',
 'MG1630805',
 'MG2380905',
 'MG2770110',
 'MG2770137',
 'MG2770145',
 'MG2770155',
 'MG2800615',
 'MG2825305',
 'MG3101102',
 'MG3127701',
 'MG3132909',
 'MG3136702',
 'MG3164605',
 'MG3171204',
 'MG3171205',
 'MG3925005',
 'MG3940925',
 'MG4390640',
 'MG4940805',
 'MG5670020',
 'MG6905900',
 'MG7200005']